import java.util.Scanner;
import java.util.Random;

class Game_Logic {

    Scanner input = new Scanner(System.in);
    Random random = new Random ();
    int random_number = random.nextInt(10);

    private int computer_number;
    private int user_number_guessed;
    private int guessed_counter;

    int get_user_number_guessed(){
        return user_number_guessed;
    }

    void set_user_number_guessed(int u_n_g){
        user_number_guessed = u_n_g;
    }

    int get_guessed_counter(){
        return user_number_guessed;
    }

    void set_guessed_counter(int u_n_g){
        user_number_guessed = u_n_g;
        user_number_guessed=0;
    }

    int get_computer_number(){
        return computer_number;
    }

    void set_computer_number(int c_r){
        user_number_guessed = c_r;
    }

    void take_user_input(){
        System.out.println("Guess the number");
        user_number_guessed = input.nextInt();

        guessed_counter++;
    }

    void is_correct_number(){

        if(user_number_guessed == random_number){
            System.out.println("Your Guess is prefect\uD83C\uDF89");
        }
        else if(user_number_guessed < random_number){
            System.out.println("wrong guess.....Guess is too low...Try again\uD83E\uDD7A");
        }
        else {
            System.out.println("wrong guess.....Guess is too High...Try again\uD83E\uDD7A1");
        }

    }

    void Show_Data(){
        System.out.println("The detailed of the selection made by user and computer");
        System.out.println("The number guess by user " +user_number_guessed);
        System.out.println("The Random Number generated by Computer " + random_number);
        int difference_c_u = user_number_guessed - random_number;
        System.out.println("The difference between your and computer guess is" + difference_c_u);
    }
    }

    public class Game {
        public static void main(String[] args) {
            Game_Logic start = new Game_Logic();
            Scanner input = new Scanner(System.in);


            while (true) {

                System.out.println("Press 1 to Play and 0 for Stop ");
                int user_choice = input.nextInt();


                if (user_choice == 0) {
                    System.out.println("Exiting...Hope to see you again");
                    break;
                } else if (user_choice == 1){
                    start.take_user_input();
                    start.is_correct_number();
                    start.Show_Data();
                }
                else{
                    System.out.println("You didn't select anything");
                }
            }
        }
    }


